### ISSUE TITLE
Not working with Blazor WebAssembly

### ISSUE THREAD

**Issue by r2d2rigo** [isc30/blazor-analytics#12] opened 2020-03-19 11:20 UTC
Hi, I added this library to a small project I'm working on and it doesn't seem to do anything at all when targeting WebAssembly.

Project details:
- .NET Core 3.1.102
- Microsoft.AspNetCore.Components.WebAssembly 3.2.0-preview2.20160.5

Neither running on local or publishing on the web shows anything in Analytics. If I copy and paste the code provided by Google into the project's index.html, it shows data when run from both places.

**Comment by isc30** [comment] 2020-03-19 14:11
Hi, do you mind pointing me to a dummy repo where I can reproduce the issue?
Thanks!

**Comment by r2d2rigo** [comment] 2020-03-19 16:42
Here you go: https://github.com/r2d2rigo/blazor-analytics-issue-12

Please put your own tracking ID in App.razor before attempting to run it.

**Comment by isc30** [comment] 2020-03-22 16:56
Hi, this seems related to trying to use it with a preview version of Blazor `3.2.0-preview2.20160.5`.
I only maintain the stable version `3.0.0`.
Feel free to clone the repo and debug the issue if you want. PRs are welcome!

**Comment by mcastellano** [comment] 2020-07-31 14:16
I know this is an old issue, but in the instructions for wasm there seems to be a step missing to add "<script src="_content/Blazor-Analytics/blazor-analytics.js"></script> to index.html.

**Comment by isc30** [comment] 2020-07-31 14:19
Oh right, do you mind adding a PR for this? I'm not in the PC atm

**Comment by isc30** [comment] 2020-09-20 15:58
Closing since the PR was merged, thanks a lot!

**Closed by isc30** 2020-09-20 15:58 UTC
